name: Deploy docs using ghp-import style

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Git credentials
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Install ghp-import
      run: pip install ghp-import

    - name: Deploy built docs (like ghp-import -n -p -f docs/)
      run: |
        ghp-import -n -f docs
        git push origin gh-pages
